FROM base/archlinux
USER root
WORKDIR /root
RUN pacman -Syy && \
    pacman -S vim neovim ruby gcc make git unzip --noconfirm 
RUN curl https://releases.hashicorp.com/terraform/0.9.4/terraform_0.9.4_linux_amd64.zip -o terraform_0.9.4_linux_amd64.zip && \
    unzip terraform_0.9.4_linux_amd64.zip && \
    mv terraform /usr/bin/terraform
ADD tests/ tests/
COPY tests.vimrc tests.vimrc
ADD vader.vim/ vader.vim/
ADD . vim-terraform-completion/
ENTRYPOINT ["/bin/sh"]
