FROM base/archlinux
USER root
WORKDIR /root
ADD example.vimrc .vimrc
ADD tests/ tests/
RUN pacman -Syy && \
    pacman -S vim neovim ruby gcc make git unzip --noconfirm 
RUN curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
RUN vim +PlugInstall +qall
RUN curl https://releases.hashicorp.com/terraform/0.9.4/terraform_0.9.4_linux_amd64.zip -o terraform_0.9.4_linux_amd64.zip && \
    unzip terraform_0.9.4_linux_amd64.zip && \
    mv terraform /usr/bin/terraform
ENTRYPOINT ["vim"]
