#!/usr/bin/env ruby
require 'nokogiri'         
require 'json'
require 'open-uri'

page = Nokogiri::HTML(open("https://www.terraform.io/docs/providers"))
provider = []

page.css(".nav a").each do |x|
  if x['href'] =~ /docs\/providers\/.*\/index.html/ then
    provider.push(x['href'])
  end
end

provider.each do |i|
  page = Nokogiri::HTML(open("https://www.terraform.io#{i}"))
  provider_name = i.split('/')[-2]
  arguments = []

  puts "Starting Provider of #{provider_name}"

  page.css(".docs-sidenav a").each do |x| 
    if not x['href'] == '#' then
      if not x['href'] == "/docs/providers/#{provider_name}/index.html" then
        if not x['href'] == '/docs/providers/index.html' then
          arguments.push(x['href'])
        end
      end
    end
  end

  result = {}

  arguments.each do |x|
    page = Nokogiri::HTML(open("https://www.terraform.io#{x}"))

    arguments = []
    attributes = []
    page.css("#argument-reference ~ ul:first-of-type").css('a').each do |i|
      if not i['name'].nil? then
        if not i['name'].include? "-" then
          arguments.push({ 'word' => i['name']})
        else
          arguments.push({ 'word' => i["name"].split("-")[0] })
        end
      end
    end
    page.css("#attributes-reference ~ ul:first-of-type").css('a').each do |i|
      if not i['name'].nil? then
        if not i['name'].include? "-" then
          attributes.push({ 'word' => i['name']})
        else
          attributes.push({ 'word' => i['name'].split("-")[0]})
        end
      end
    end

    page.css("#attribute-reference ~ ul:first-of-type").css('a').each do |i|
      if not i['name'].nil? then
        if not i['name'].include? "-" then
          attributes.push({ 'word' => i['name']})
        else
          attributes.push({ 'word' => i['name'].split("-")[0]})
        end
      end
    end

    name = x.split('/')[-1].split(".html")[0]
    result[name] = { "provider" => provider_name, "arguments" => arguments, "attributes" => attributes }
    puts "Finish #{name} of #{provider_name}"
  end

  if provider_name == "do" then 
    provider_name = "digitalocean"
  end

  File.open("provider_json/#{provider_name}.json", 'w') { |file| file.write(JSON.generate(result)) }
end
