#!/usr/bin/env ruby
require 'json'
if File.exist?("#{ARGV[0]}/terraform.tfstate")
  state_data = JSON.parse(File.read("#{ARGV[0]}/terraform.tfstate"))
  puts "#{ARGV[2]}: #{state_data['modules'][0]['resources'][ARGV[1]]['primary']['attributes'][ARGV[2]]}"
else
  puts "No State file found"
end
